name: Build and Deploy
on:
  push:
    branches: [main]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set EGI Check-in issuer and client ID
        run: |
          sed -i -e "s|\$EGI_CHECKIN_ISSUER|${{ secrets.EGI_CHECKIN_ISSUER }}|g"  src/env.ts
          sed -i -e "s|\$EGI_CHECKIN_CLIENT_ID|${{ secrets.EGI_CHECKIN_CLIENT_ID }}|g"  src/env.ts
          sed -i -e "s|\$AI4EOSC_KEYCLOAK_ISSUER|${{ secrets.AI4EOSC_KEYCLOAK_ISSUER }}|g"  src/env.ts
          sed -i -e "s|\$DEPLOY_CONTAINER|${{ env.DEPLOY_CONTAINER }}|g"  src/env.ts
          sed -i -e "s|\$AI4EOSC_KEYCLOAK_CLIENT_ID|${{ secrets.AI4EOSC_KEYCLOAK_CLIENT_ID }}|g"  src/env.ts
          sed -i -e "s|\$AI4EOSC_KEYCLOAK_CLIENT_SECRET|${{ secrets.AI4EOSC_KEYCLOAK_CLIENT_SECRET }}|g"  src/env.ts
          sed -i -e "s|\$GRYCAP_KEYCLOAK_ISSUER|${{ secrets.GRYCAP_KEYCLOAK_ISSUER }}|g"  src/env.ts
          sed -i -e "s|\$GRYCAP_KEYCLOAK_CLIENT_ID|${{ secrets.GRYCAP_KEYCLOAK_CLIENT_ID }}|g"  src/env.ts
          sed -i -e "s|\$GRYCAP_KEYCLOAK_CLIENT_SECRET|${{ secrets.GRYCAP_KEYCLOAK_CLIENT_SECRET }}|g"  src/env.ts

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Include CNAME
        run: echo "${{ secrets.DOMAIN }}" > ./dist/CNAME

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
